'use client';

import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { CheckCircle2, Loader2, Plus, Trash2 } from 'lucide-react';

type Service = { name: string; price: number; duration: number };
type Hours = { weekday: number; start: string; end: string };
const days = ['Domingo', 'Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta', 'Sábado'];
const empty = { name: '', city: '', instagram: '', timezone: 'America/Sao_Paulo', goal: '', profile: { tone: '', audience: '', differentiators: '', policies: '', faq: '', instagramVoice: '', approval: false, enabled: false }, services: [{ name: '', price: 0, duration: 60 }], hours: [1,2,3,4,5].map(weekday => ({ weekday, start: '09:00', end: '18:00' })) };

export default function SetupPage() {
  const router = useRouter();
  const [form, setForm] = useState(empty);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState('');
  useEffect(() => { fetch('/api/salons/setup').then(async r => { if (r.status === 401) { router.replace('/auth/login'); return; } if (!r.ok) throw new Error('Falha ao carregar'); const d = await r.json(); setForm({
    name: d.salon?.name || '', city: d.salon?.city || '', instagram: d.salon?.instagram || '', timezone: d.salon?.timezone || 'America/Sao_Paulo', goal: d.salon?.goal || '',
    profile: d.profile || empty.profile,
    services: d.services?.length ? d.services.map((s: Service) => ({ name: s.name, price: Number(s.price), duration: Number(s.duration) })) : empty.services,
    hours: d.hours?.length ? d.hours : empty.hours,
  }); }).catch(() => setError('Não foi possível carregar o salão.')).finally(() => setLoading(false)); }, [router]);
  function field(key: keyof typeof empty.profile, value: string | boolean) { setForm(f => ({ ...f, profile: { ...f.profile, [key]: value } })); }
  async function save(event: React.FormEvent) { event.preventDefault(); setSaving(true); setError(''); try {
    const res = await fetch('/api/salons/setup', { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) });
    const data = await res.json(); if (!res.ok) throw new Error(data.error || 'Erro ao salvar.'); const plan = new URLSearchParams(window.location.search).get('plan'); router.push(plan === 'enterprise' || plan === 'starter' ? `/checkout?plan=${plan}` : '/'); router.refresh();
  } catch (e) { setError(e instanceof Error ? e.message : 'Falha ao salvar.'); } finally { setSaving(false); } }
  if (loading) return <div className="min-h-screen grid place-items-center"><Loader2 className="animate-spin"/></div>;
  const input = 'mt-1 w-full rounded-xl border border-border bg-background px-4 py-3 outline-none focus:border-primary';
  return <main className="min-h-screen bg-background p-5 md:p-10"><form onSubmit={save} className="mx-auto max-w-4xl space-y-7">
    <header><p className="text-sm font-semibold text-primary">SalonPilot · Configuração do salão</p><h1 className="text-3xl font-bold mt-2">Ensine sua assistente sobre o seu negócio</h1><p className="text-muted-foreground mt-2">Esses dados orientam o atendimento no WhatsApp e os rascunhos de conteúdo do Instagram. Você poderá revisá-los depois.</p></header>
    <section className="rounded-2xl border p-6 space-y-4"><h2 className="text-xl font-semibold">1. Salão e objetivos</h2><div className="grid md:grid-cols-2 gap-4">
      {([['name','Nome do salão'],['city','Cidade'],['instagram','Instagram (@perfil)'],['goal','Objetivo principal de crescimento']] as const).map(([key,label]) => <label key={key} className="text-sm font-medium">{label}<input required={key !== 'instagram'} value={form[key]} onChange={e => setForm(f => ({ ...f, [key]: e.target.value }))} className={input}/></label>)}
    </div><label className="block text-sm">Fuso horário<input value={form.timezone} onChange={e => setForm(f => ({ ...f, timezone: e.target.value }))} className={input}/></label></section>
    <section className="rounded-2xl border p-6 space-y-4"><h2 className="text-xl font-semibold">2. Serviços e preços oficiais</h2><p className="text-sm text-muted-foreground">A IA só pode informar os valores cadastrados aqui.</p>{form.services.map((service, i) => <div key={i} className="grid grid-cols-[1fr_90px_90px_32px] gap-2 items-end"><label className="text-xs">Serviço<input required minLength={2} value={service.name} onChange={e => setForm(f => ({ ...f, services: f.services.map((s,j) => j===i ? { ...s, name:e.target.value } : s) }))} className={input}/></label><label className="text-xs">R$<input required type="number" min="0" step="0.01" value={service.price} onChange={e => setForm(f => ({ ...f, services: f.services.map((s,j) => j===i ? { ...s, price:Number(e.target.value) } : s) }))} className={input}/></label><label className="text-xs">Minutos<input required type="number" min="10" value={service.duration} onChange={e => setForm(f => ({ ...f, services: f.services.map((s,j) => j===i ? { ...s, duration:Number(e.target.value) } : s) }))} className={input}/></label><button type="button" aria-label="Remover serviço" disabled={form.services.length===1} onClick={() => setForm(f => ({...f,services:f.services.filter((_,j)=>j!==i)}))} className="pb-3 disabled:opacity-40"><Trash2 size={17}/></button></div>)}<button type="button" onClick={() => setForm(f => ({...f,services:[...f.services,{name:'',price:0,duration:60}]}))} className="text-sm text-primary flex gap-2 items-center"><Plus size={16}/> Adicionar serviço</button></section>
    <section className="rounded-2xl border p-6 space-y-4"><h2 className="text-xl font-semibold">3. Horários de atendimento</h2><p className="text-sm text-muted-foreground">Dias sem horário não serão oferecidos para agendamento.</p><div className="grid sm:grid-cols-2 gap-3">{days.map((day,weekday)=>{const h=form.hours.find(x=>x.weekday===weekday);return <div key={day} className="flex items-center gap-2"><label className="w-24 text-sm"><input type="checkbox" checked={!!h} onChange={e=>setForm(f=>({...f,hours:e.target.checked?[...f.hours,{weekday,start:'09:00',end:'18:00'}]:f.hours.filter(x=>x.weekday!==weekday)}))}/> {day}</label>{h && <><input type="time" aria-label={`Início ${day}`} value={h.start} onChange={e=>setForm(f=>({...f,hours:f.hours.map(x=>x.weekday===weekday?{...x,start:e.target.value}:x)}))} className="rounded border p-1"/><input type="time" aria-label={`Fim ${day}`} value={h.end} onChange={e=>setForm(f=>({...f,hours:f.hours.map(x=>x.weekday===weekday?{...x,end:e.target.value}:x)}))} className="rounded border p-1"/></>}</div>})}</div></section>
    <section className="rounded-2xl border p-6 space-y-4"><h2 className="text-xl font-semibold">4. Como a IA deve agir</h2><div className="grid md:grid-cols-2 gap-4">{([['audience','Público principal','Ex.: mulheres da região que procuram cuidados recorrentes'],['differentiators','Diferenciais reais','Ex.: atendimento individual, profissionais especializados'],['tone','Tom no WhatsApp','Ex.: acolhedor, objetivo e sem excesso de emojis'],['instagramVoice','Tom no Instagram','Ex.: educativo e elegante, com chamada para agendamento']] as const).map(([key,label,placeholder])=><label key={key} className="text-sm font-medium">{label}<textarea required minLength={3} maxLength={key==='differentiators'?800:600} placeholder={placeholder} value={form.profile[key]} onChange={e=>field(key,e.target.value)} className={input} rows={3}/></label>)}</div><label className="block text-sm font-medium">Políticas do salão: cancelamento, sinal, atrasos, promoções e assuntos que precisam de atendente<textarea required minLength={10} maxLength={1600} value={form.profile.policies} onChange={e=>field('policies',e.target.value)} className={input} rows={4} placeholder="Ex.: cancelamentos com 24 horas de antecedência; preços apenas da tabela; reclamações passam para atendente."/></label><label className="block text-sm font-medium">Perguntas frequentes (opcional)<textarea maxLength={1600} value={form.profile.faq} onChange={e=>field('faq',e.target.value)} className={input} rows={3}/></label></section>
    <section className="rounded-2xl border p-6 space-y-4"><h2 className="text-xl font-semibold">5. Revisão e ativação</h2><p className="text-sm text-muted-foreground">O WhatsApp não responde automaticamente até que você aprove estas informações e ative a assistente. O Instagram gera rascunhos, sem publicar sozinho.</p><label className="flex gap-2 text-sm"><input type="checkbox" required checked={form.profile.approval} onChange={e=>field('approval',e.target.checked)}/> Conferi os serviços, preços, horários e políticas.</label><label className="flex gap-2 text-sm"><input type="checkbox" checked={form.profile.enabled} onChange={e=>field('enabled',e.target.checked)}/> Ativar respostas automáticas do WhatsApp quando o canal estiver conectado.</label></section>
    {error && <p role="alert" className="text-destructive">{error}</p>}
    <div className="flex justify-end gap-3"><button type="button" onClick={()=>router.push('/')} className="rounded-xl border px-5 py-3">Voltar</button><button disabled={saving} className="rounded-xl bg-primary text-primary-foreground px-6 py-3 font-semibold disabled:opacity-50 flex gap-2 items-center">{saving?<Loader2 size={18} className="animate-spin"/>:<CheckCircle2 size={18}/>} Salvar configuração</button></div>
  </form></main>;
}
